---
- name: create users on specific hosts & upload ssh keys
  hosts: webservers
  become: true
  vars_files: 
     - variables/userslist
     - secret.yml
  tasks:
    - name: Create users on webservers group
      user:
        name: "{{item.username}}"
        uid: "{{item.uid}}"
        append: true
        groups: wheel
        shell: "{{item.shell}}"
        password: "{{user_password | password_hash('sha512')}}"
      loop: "{{users}}"
      when: item.uid is regex('^1')

    - name: Upload ssh keys
      authorized_key:
         user: "{{item.username}}"
         state: present
         key: "{{lookup('file', '/home/automation/.ssh/id_rsa.pub')}}"
      loop: "{{users}}"
      when: item.uid is regex('^1')


- name: create users on specific hosts & upload ssh keys
  hosts: database
  become: true
  vars_files: 
     - variables/userslist
     - secret.yml
  tasks:
    - name: Create users on webservers group
      user:
        name: "{{item.username}}"
        uid: "{{item.uid}}"
        shell: "{{item.shell}}"
        password: "{{user_password | password_hash('sha512')}}"
        append: true
        groups: wheel
      loop: "{{users}}"
      when: item.uid is regex('^2')

    - name: Upload ssh keys
      authorized_key:
         user: "{{item.username}}"
         state: present
         key: "{{lookup('file', '/home/automation/.ssh/id_rsa.pub')}}"
      loop: "{{users}}"
      when: item.uid is regex('^2')

