---
- name: Create users and upload ssh keys
  hosts: localhost
  vars:
    - users:
       - {username: testuser1, shell: /bin/bash}
       - {username: testuser2, shell: /bin/bash}
  tasks:
    - name: Create users
      user:
        name: "{{item.username}}"
        shell: "{{item.shell}}"
        generate_ssh_key: true
        ssh_key_file: "{{item.username}}"
      loop: "{{users}}"
