---
- name: testing crontab
  hosts: localhost
  become: true
  tasks:

    - name: run a cron job
      cron:
        name: flogger
        minute: "*/2"
        job: "echo hello >> /tmp/cronsible"



    - name: remove a cron job
      cron:
        name: "flogger"
        state: absent
      tags:
        - remover
