---
- name: reboot the machine
  hosts: managed-node-3
  become: true
  tasks:


    - name: create a cron job that will pring something on reboot
      cron:
        name: rebooter
        special_time: reboot
        job: "echo rebooted at $(date) >> /tmp/reboot.log"
        state: present



    - name: reboot the machine
      reboot:
        msg: reboot started by mohie
        test_command: whoami



    - name: we did it
      debug:
        msg: "{{inventory_hostname}}"
      tags:
        - reboot
