- import_playbook: motd.yml

- import_playbook: sshd.yml

- import_playbook: users.yml

- import_playbook: cron.yml

- import_playbook: repository.yml

- import_playbook: mysql.yml

- import_playbook: tomcat.yml

- import_playbook: haproxy.yml

- import_playbook: sysctl.yml

- import_playbook: archive.yml

- import_playbook: facts.yml

- import_playbook: packages.yml

- import_playbook: services.yml

- import_playbook: server_list.yml

