---
- name: configure sshd bla
  hosts: all
  tasks:

  - name: Set banner to motd
    lineinfile:
      regexp: '^#Banner'
      line: 'Banner /etc/motd'
      path: /etc/ssh/sshd_config


  - name: Set Maxauth tries to 3
    lineinfile:
      regexp: '^MaxAuthTries.*'
      line: 'MaxAuthTries  6'
      path: /etc/ssh/sshd_config

