---
- name: create vdo volume
  hosts: managed-node-1
  tasks:

    - name: check storage size
      setup:


    - name: debug
      debug:
        msg: "{{ansible_facts['devices']['sdb']['size'] | regex_search('[0-9].*\\.[0-9]+') }}"
      when: false

    - name: vdo crete
      vdo:
        name: vdo1
        device: /dev/sdb
        logicalsize: 1T
        state: present
