---
- name: set_bool
  seport:
    setype: http_port_t
    state: present
    ports: "{{apache_port}}"
    proto: tcp

- name: set_context
  sefcontext:
    target: '/webserver(/.*)?'
    setype: httpd_sys_content_t
    state: present

- name: restart_apache
  service:
    name: "{{apache_service}}"
    state: restarted
    enabled: true

# handlers file for apache
