---
- name: copy blackfacts
  hosts: blacksheep
  tasks:
    - name: copy local facts
      copy:
        src: black_facts.fact
        dest: /etc/ansible/facts.d/
    - name: install packages based on those facts
      yum:
        name: "{{ansible_facts['ansible_local']['black_facts']['blackfacts']['web_server']}}"
        state: latest
    - name: Activate local service fact
      service:
        name: "{{ansible_facts['ansible_local']['black_facts']['blackfacts']['service']}}"
        enabled: true
        state: started
...
