---
- name: create a partition with parted
  parted:
    device: : /dev/sdb
    number: 1
    state: present
    part_start: 1MB
    part_end: 800MB
    flags:
      - lvm

- name: create vg called vg_database
  lvg:
    vg: vg_database
    pvs: /dev/sdb1

- name: create lvm
  lvol:
    vg: vg_database
    lv: lv_mysql
    size: 512m
- name: create filesystem
  filesystem:
    fstype: xfs
    dev: /dev/vg_database/lv_mysql
- name: mount to /mnt/mysql_backups
  mount: 
    src: /dev/vg_database/lv_mysql
    dest: /mnt/mysql_backups

- name: yum install mysql-community-server
  yum:
    name: mysql-community-server
    state: latest
