---
- name: generate some hosts file on just one node
  hosts: all
  tasks: 


    - name: tempalte again
      template:
        src: hosts.j2
        dest: /etc/hosts.txt
        force: true
        owner: "{{ansible_user}}"
        group: "{{ansible_user}}"
