---
- name: setup webservers
  hosts: webservers
  tasks:

    - name: install two pacakges
      yum:
        name:
          - mod_ssl
          - php
          - firewalld
     
    - name: service
      service:
        name: firewalld
        state: started
        enabled: true


    - name: template
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
        force: yes
