---
- name: install remote repository
  hosts: all
  become: true
  tasks:


    - name: create repository
      yum_repository:
        description: "Ansible local repo"
        name: ansible-control
        baseurl: ftp://10.0.1.1/pub/
        enabled: yes
 
   # - name: install rpm key
    #  rpm_key:
     #   key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

    - name:
      yum_repository:
        gpgkey: /etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org
        baseurl: "http://elrepo.org/linux/elrepo/el8/$basearch/"
        description: "elrepo"
        gpgcheck: yes
        enabled: yes
        name: elrepo
